Web_Final_1/Web_Final/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web_Final.Models
{
    public class Post
    {
        public int ID { set; get; }
        [Required(ErrorMessage = "Phải nhập nội dung")]
        [StringLength(50, ErrorMessage = "Số lượng ký tự trong khoảng 10 - 50", MinimumLength = 10)]
        public String Title { set; get; }
        [Required(ErrorMessage = "Phải nhập nội dung")]
        [RegularExpression(@"^.{30,}$", ErrorMessage = "Nhập tối thiểu 30 ký tự")]
        public String Body { set; get; }

        [DataType(DataType.DateTime)]
        public DateTime DateCreated { set; get; }

        [DataType(DataType.DateTime)]
        public DateTime DateUpdated { set; get; }
        //
        //
        public string Picture { get; set; }
        //
        public virtual UserProfile UserProfile { set; get; }
        public int UserProfileUserId { set; get; }
        //
        public virtual ICollection<Tag> Tags { set; get; }
        //
        public virtual ICollection<Comment> Comments { set; get; }
        //
        //
        public int PostTypeID { set; get; }
        public virtual PostType PostType { set; get; }
        
    }
}

Web_Final_1/Web_Final/Models/PostType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web_Final.Models
{
    public class PostType
    {
        public int ID { set; get; }

        public String NameType { set; get; }

        public String AdminFlag { set; get; }

        public String RelationshipFlag { set; get; }

        //
        public virtual ICollection<Post> Posts { set; get; }
    }
}

Web_Final_1/Web_Final/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Final.Models;

namespace Web_Final.Controllers
{
    public class CommentController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Post);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment comment,int idpost)
        {
            if (ModelState.IsValid)
            {
                comment.PostID = idpost;
                comment.DateCreated = DateTime.Now;
                comment.DateUpdated = DateTime.Now;
   
                db.Comments.Add(comment);
                db.SaveChanges();
                return PartialView("viewContent", comment);
                //return RedirectToAction("Details/"+idpost,"Post");
            }

            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.DateUpdated = DateTime.Now;
                //comment.LastTime = DateTime.Now;
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Web_Final_1/Web_Final/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_Final.Models;

namespace Web_Final.Controllers
{
    public class PostController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Post/

        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.UserProfile).Include(p => p.PostType);
            return View(posts.ToList());
        }

        //
        // GET: /Post/Details/5

        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewData["idpost"] = id;
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            ViewBag.PostTypeID = new SelectList(db.PostTypes, "ID", "NameType");
            return View();
        }

        //
        // POST: /Post/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post, string Content)
        {
            if (ModelState.IsValid)
            {
                post.DateCreated = DateTime.Now;
                post.DateUpdated = DateTime.Now;
                //Gan id vao cho post
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName })
                       .Where(y => y.UserName == User.Identity.Name).Single().UserId;
                post.UserProfileUserId = userid;

                //Tao list cac Tag
                List<Tag> Tags = new List<Tag>();
                //Tach cac Tag theo dau ,
                string[] TagContent = Content.Split(',');
                //Lap cac Tag vua tach
                foreach (string item in TagContent)
                {
                    //Tim xem Tag Content da co hay chua
                    Tag tagExits = null;
                    var ListTag = db.Tags.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        //Neu co Tag roi thi add them post vao
                        tagExits = ListTag.First();
                        tagExits.Posts.Add(post);
                    }
                    else
                    {
                        //neu chua co Tag thi tao moi
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.Posts = new List<Post>();
                        tagExits.Posts.Add(post);
                    }
                    //add vao List cac Tag
                    Tags.Add(tagExits);
                }
                //Gan List Tag cho Post
                post.Tags = Tags;

                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            //
            ViewBag.PostTypeID = new SelectList(db.PostTypes, "ID", "NameType", post.PostTypeID);
            return View(post);
        }
        //Click vao Tag de hien ra cac Post
        [AllowAnonymous]
        public ActionResult _Search(string searchString)
        {
            var posts = from p in db.Posts select p;
            if (!string.IsNullOrEmpty(searchString))
            {
                posts = posts.Where(y => y.Tags.Any(t => t.Content.Contains(searchString)));
            }
            return View(posts);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            ViewBag.PostTypeID = new SelectList(db.PostTypes, "ID", "NameType", post.PostTypeID);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                post.DateUpdated = DateTime.Now;
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
                
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        // tao hinh
        [HttpPost]
        
        public ActionResult FileUpload(Post post, HttpPostedFileBase file,string Content)
        {
            if (ModelState.IsValid)
            {


                post.DateCreated = DateTime.Now;
                post.DateUpdated = DateTime.Now;
                //Gan id vao cho post
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName })
                       .Where(y => y.UserName == User.Identity.Name).Single().UserId;
                post.UserProfileUserId = userid;

                //Tao list cac Tag
                List<Tag> Tags = new List<Tag>();
                //Tach cac Tag theo dau ,
                string[] TagContent = Content.Split(',');
                //Lap cac Tag vua tach
                foreach (string item in TagContent)
                {
                    //Tim xem Tag Content da co hay chua
                    Tag tagExits = null;
                    var ListTag = db.Tags.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        //Neu co Tag roi thi add them post vao
                        tagExits = ListTag.First();
                        tagExits.Posts.Add(post);
                    }
                    else
                    {
                        //neu chua co Tag thi tao moi
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.Posts = new List<Post>();
                        tagExits.Posts.Add(post);
                    }
                    //add vao List cac Tag
                    Tags.Add(tagExits);
                }
                //Gan List Tag cho Post
                post.Tags = Tags;



                if (file != null)
                {
                    string ImageName = System.IO.Path.GetFileName(file.FileName);
                    long t = 0;
                    string ID = db.Posts
                            .Max(c => c.Picture.Substring(2, c.Picture.Length - 6));
                    try
                    {
                        t = int.Parse(ID);
                    }
                    catch
                    {
                    }
                    t++;
                    ID = "MA" + t.ToString() + ".jpg";

                    string physicalPath = Server.MapPath("~/images/" + ID);

                    file.SaveAs(physicalPath);
                    post.DateCreated = DateTime.Now;
                    post.DateUpdated = DateTime.Now;

                    post.Picture = ID;
                    db.Posts.Add(post);
                    db.SaveChanges();
                }
                else
                {

                    post.DateCreated = DateTime.Now;
                    post.DateUpdated = DateTime.Now;

                    post.Picture = "NH0.jpg";
                    db.Posts.Add(post);
                    db.SaveChanges();
                }
                //Display records
                return RedirectToAction("Details", "PostType", new { id = post.PostTypeID });
            }
            //SF
            ViewBag.PostTypeID = new SelectList(db.PostTypes, "PostTypeID", "NameType", post.PostTypeID);
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }
        //------------------------------------------------------
    }
}

Web_Final_1/Web_Final/Views/Post/Create.cshtml
@model Web_Final.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@*@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)*@
@using (Html.BeginForm("FileUpload", "Post", FormMethod.Post,
                    new { enctype = "multipart/form-data" }))
{
    <fieldset>
        <legend>Post</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        Chọn kiểu bài viết:
        <div class="editor-field">
            @Html.DropDownList("PostTypeID", String.Empty)
            @Html.ValidationMessageFor(model => model.PostTypeID)
        </div>

       
        <div class="editor-label">
            Tag:
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => new Web_Final.Models.Tag().Content)
            @Html.ValidationMessageFor(model => new Web_Final.Models.Tag().Content)
        </div>
        Ðang hình: <input type="file" name="file" id="file" style="width: 100%;" /> <br />
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web_Final_1/Web_Final/Views/Post/Delete.cshtml
@model Web_Final.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateUpdated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateUpdated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Web_Final_1/Web_Final/Views/Post/Details.cshtml
@model Web_Final.Models.Post

@{
    ViewBag.Title = "Details";
}

@*<h2>Details</h2>*@

<fieldset>
    <legend>Post</legend>

    @*<div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>*@
    <div class="display-field">
        <h2>@Html.DisplayFor(model => model.Title)</h2>
    </div>
    <em>Được đăng bởi <strong> @Html.DisplayFor(model=>model.UserProfile.UserName)</strong> lúc @Html.DisplayFor(model=>model.DateCreated)</em>
    <em><br/>Chỉnh sửa @Html.DisplayFor(model=>model.DateUpdated)</em>
    @*<div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>*@
    <br/>Nội dung
    <br/>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    @*<div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateUpdated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateUpdated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>*@
    @*them hinh*@
    <img src="\images\@Model.Picture" width="250" height="250"/>
    <!--Hien cac Tag cua Post tuong ung-->
    <div class="post-tags">
        <b>Tags:</b>
        @foreach (var i in Model.Tags)
        {
            <b> @Html.ActionLink(i.Content, "_Search", new { searchString = i.Content });</b>
            //@Html.ActionLink("","", "Tag/" +"Details/" + i.TagID)
        }
    </div>
    
</fieldset>

@Html.Partial("_addComment", new Web_Final.Models.Comment(), ViewData)

<fieldset>
    <legend>Comment</legend>
    <h2>Comment:</h2>
    <div id="result">

        @foreach (var comment in Model.Comments.OrderByDescending(x => x.DateCreated).Take(10))
        {
            <div class="display-field">
                @if (comment.LastTime < 1)
                {
                    <b>Cách đây vài giây trước</b>
                }
                else
                {
                    if (comment.LastTime < 3)
                    {
                        <b>Cách đây vài phút</b>
                    }
                    else
                    {
                        if (comment.LastTime < 60)
                        {
                            <b>Cách đây: @Html.DisplayFor(x => comment.LastTime) phút</b>
                        }
                        else
                        {
                            if (comment.LastTime < 60 * 24 - 1)
                            {
                                <b>Cách đây: @(comment.LastTime / 60) tiếng</b>
                            }
                            else
                            {
                                <b>Đăng ngày @comment.DateCreated</b>
                            }
                        }
                    }
                }
            </div>

            <div class="display-field">
                @Html.DisplayFor(x => comment.Body)
            </div>
        }
    </div>
</fieldset>

<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Web_Final_1/Web_Final/Views/Post/Edit.cshtml
@model Web_Final.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        @Html.HiddenFor(model => model.DateCreated)
        @Html.HiddenFor(model => model.DateUpdated)
        @Html.HiddenFor(model => model.UserProfileUserId)
        @Html.HiddenFor(model=>model.PostTypeID)
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web_Final_1/Web_Final/Views/Post/FileUpload.cshtml
@model Web_Final.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@*@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)*@
@using (Html.BeginForm("FileUpload", "Post", FormMethod.Post,
                    new { enctype = "multipart/form-data" }))
{
    <fieldset>
        <legend>Post</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        Chọn kiểu bài viết:
        <div class="editor-field">
            @Html.DropDownList("PostTypeID", String.Empty)
            @Html.ValidationMessageFor(model => model.PostTypeID)
        </div>


        <div class="editor-label">
            Tag:
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => new Web_Final.Models.Tag().Content)
            @Html.ValidationMessageFor(model => new Web_Final.Models.Tag().Content)
        </div>
        Ðang hình: <input type="file" name="file" id="file" style="width: 100%;" /> <br />
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web_Final_1/Web_Final/Views/Post/Index.cshtml
@model IEnumerable<Web_Final.Models.Post>

@{
    //ViewBag.Title = "Index";
}


<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<style>
    table{
        border:1px solid black;
        border-collapse: collapse;
    }
</style>

@Html.Partial("_khungSearch", new Web_Final.Models.Post(), ViewData)

@*<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateUpdated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateUpdated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>

    }
</table>*@
<div style="width:800px">
    @foreach (var item in Model)
    {
        //

                           

        //
        <h4>@Html.ActionLink(item.Title, "Details", new { id = item.ID })</h4>
    <div style="border: 1px solid black; border-collapse: collapse;width:500px">
        @item.Body.Substring(0,250) <em>
            @Html.ActionLink("...đọc thêm", "Details", new { id = item.ID }) |
        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
    </em>
    <br />
</div>
    }
</div>

Web_Final_1/Web_Final/Views/Post/_Search.cshtml
@model IEnumerable <Web_Final.Models.Post>

@{
    ViewBag.Title = "_Search";
}

<h2>Post</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


@Html.Partial("_khungSearch", new Web_Final.Models.Post(), ViewData)

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Tags.Select(x => x.Content))
        </th>*@

        <th></th>
    </tr>

    @foreach(var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Tags.Select(x=>x.Content).Single())
            </td>*@
            <td>
                
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

Web_Final_1/Web_Final/Views/Post/_addComment.cshtml
@model Web_Final.Models.Comment

@using (Html.BeginForm("Create", "Comment", FormMethod.Post, new { id = "my-form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Comment</legend>
        <h2>Add Comment</h2>

        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.Author)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Author)
            @Html.ValidationMessageFor(model => model.Author)
        </div>


        @Html.Hidden("idpost", ViewData["idpost"])


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<script src="~/Scripts/addComment.js"></script>

Web_Final_1/Web_Final/Views/Post/_khungSearch.cshtml
@model Web_Final.Models.Post

@using (Html.BeginForm("_Search", "Post", FormMethod.Post))
{
    <fieldset style="border: 10px; margin: 0; padding: 0;" >
        <div>
            Find: @Html.TextBox("searchString")
            <input type="submit" value="Search" />
        </div>
    </fieldset>
}